<?php

/**
 * This is the model base class for the table "{{node}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Node".
 *
 * Columns in table "{{node}}" available as properties of the model,
 * followed by relations of table "{{node}}" available as properties of the model.
 *
 * @property integer $node_id
 * @property string $node_hash_id
 * @property string $system
 * @property string $cpu
 * @property string $hard_disk
 * @property string $created_at
 * @property string $updated_at
 *
 * @property NodeHasTask[] $nodeHasTasks
 * @property NodeMoment[] $nodeMoments
 */
abstract class BaseNode extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{node}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Node|Nodes', $n);
	}

	public static function representingColumn() {
		return 'node_hash_id';
	}

	public function rules() {
		return array(
			array('node_hash_id', 'required'),
			array('node_hash_id', 'length', 'max'=>256),
			array('system, cpu, hard_disk', 'length', 'max'=>1024),
			array('created_at, updated_at', 'safe'),
			array('system, cpu, hard_disk, created_at, updated_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('node_id, node_hash_id, system, cpu, hard_disk, created_at, updated_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'nodeHasTasks' => array(self::HAS_MANY, 'NodeHasTask', 'node_id'),
			'nodeMoments' => array(self::HAS_MANY, 'NodeMoment', 'node_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'node_id' => Yii::t('app', 'Node'),
			'node_hash_id' => Yii::t('app', 'Node Hash'),
			'system' => Yii::t('app', 'System'),
			'cpu' => Yii::t('app', 'Cpu'),
			'hard_disk' => Yii::t('app', 'Hard Disk'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'nodeHasTasks' => null,
			'nodeMoments' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('node_id', $this->node_id);
		$criteria->compare('node_hash_id', $this->node_hash_id, true);
		$criteria->compare('system', $this->system, true);
		$criteria->compare('cpu', $this->cpu, true);
		$criteria->compare('hard_disk', $this->hard_disk, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}