<?php

/**
 * This is the model base class for the table "{{node_moment}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NodeMoment".
 *
 * Columns in table "{{node_moment}}" available as properties of the model,
 * followed by relations of table "{{node_moment}}" available as properties of the model.
 *
 * @property integer $node_moment_id
 * @property integer $node_id
 * @property string $node_moment_hash_id
 * @property string $cpu_usage
 * @property string $memory_usage
 * @property string $hard_disk_usage
 * @property string $tempurature
 * @property string $weather
 * @property string $created_at
 *
 * @property Node $node
 */
abstract class BaseNodeMoment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{node_moment}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'NodeMoment|NodeMoments', $n);
	}

	public static function representingColumn() {
		return 'node_moment_hash_id';
	}

	public function rules() {
		return array(
			array('node_id, node_moment_hash_id', 'required'),
			array('node_id', 'numerical', 'integerOnly'=>true),
			array('node_moment_hash_id, hard_disk_usage, tempurature, weather', 'length', 'max'=>256),
			array('cpu_usage, memory_usage', 'length', 'max'=>1024),
			array('created_at', 'safe'),
			array('cpu_usage, memory_usage, hard_disk_usage, tempurature, weather, created_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('node_moment_id, node_id, node_moment_hash_id, cpu_usage, memory_usage, hard_disk_usage, tempurature, weather, created_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'node' => array(self::BELONGS_TO, 'Node', 'node_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'node_moment_id' => Yii::t('app', 'Node Moment'),
			'node_id' => null,
			'node_moment_hash_id' => Yii::t('app', 'Node Moment Hash'),
			'cpu_usage' => Yii::t('app', 'Cpu Usage'),
			'memory_usage' => Yii::t('app', 'Memory Usage'),
			'hard_disk_usage' => Yii::t('app', 'Hard Disk Usage'),
			'tempurature' => Yii::t('app', 'Tempurature'),
			'weather' => Yii::t('app', 'Weather'),
			'created_at' => Yii::t('app', 'Created At'),
			'node' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('node_moment_id', $this->node_moment_id);
		$criteria->compare('node_id', $this->node_id);
		$criteria->compare('node_moment_hash_id', $this->node_moment_hash_id, true);
		$criteria->compare('cpu_usage', $this->cpu_usage, true);
		$criteria->compare('memory_usage', $this->memory_usage, true);
		$criteria->compare('hard_disk_usage', $this->hard_disk_usage, true);
		$criteria->compare('tempurature', $this->tempurature, true);
		$criteria->compare('weather', $this->weather, true);
		$criteria->compare('created_at', $this->created_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}